spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/adopet
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  mail:
    host: smtp.example.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
